### PR TITLE
add pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Comment by vooon** [comment]
Looks like you missed with the repo, don't think myheat operates in Portugal.

**Comment by ViPeR5000** [comment]
I translante all repo add in hacs from home assistant :)

**Comment by vooon** [comment]
@ViPeR5000 ah, okay, thanks! But the file looks like it for some other plugin, check the English one: https://github.com/vooon/hass-myheat/blob/master/custom_components/myheat/translations/en.json

**Comment by ViPeR5000** [comment]
> @ViPeR5000 ah, okay, thanks! But the file looks like it for some other plugin, check the English one: https://github.com/vooon/hass-myheat/blob/master/custom_components/myheat/translations/en.json

My mistake :( its fixed now

**Review by vooon — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
